version: 2
updates:
- package-ecosystem: uv
  directory: "/"
  schedule:
    interval: monthly
  groups:
    all-dependencies:
      patterns: ["*"]
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    all-actions:
      patterns: ["*"]
